#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7EA53E6D798DB404 (charles.kerr@canonical.com)
#
Name     : libindicator
Version  : 12.10.1
Release  : 4
URL      : https://launchpad.net/libindicator/12.10/12.10.1/+download/libindicator-12.10.1.tar.gz
Source0  : https://launchpad.net/libindicator/12.10/12.10.1/+download/libindicator-12.10.1.tar.gz
Source1  : https://launchpad.net/libindicator/12.10/12.10.1/+download/libindicator-12.10.1.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: libindicator-data = %{version}-%{release}
Requires: libindicator-lib = %{version}-%{release}
Requires: libindicator-libexec = %{version}-%{release}
Requires: libindicator-license = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
Patch1: libm.patch

%description


%package data
Summary: data components for the libindicator package.
Group: Data

%description data
data components for the libindicator package.


%package dev
Summary: dev components for the libindicator package.
Group: Development
Requires: libindicator-lib = %{version}-%{release}
Requires: libindicator-data = %{version}-%{release}
Provides: libindicator-devel = %{version}-%{release}
Requires: libindicator = %{version}-%{release}

%description dev
dev components for the libindicator package.


%package lib
Summary: lib components for the libindicator package.
Group: Libraries
Requires: libindicator-data = %{version}-%{release}
Requires: libindicator-libexec = %{version}-%{release}
Requires: libindicator-license = %{version}-%{release}

%description lib
lib components for the libindicator package.


%package libexec
Summary: libexec components for the libindicator package.
Group: Default
Requires: libindicator-license = %{version}-%{release}

%description libexec
libexec components for the libindicator package.


%package license
Summary: license components for the libindicator package.
Group: Default

%description license
license components for the libindicator package.


%prep
%setup -q -n libindicator-12.10.1
cd %{_builddir}/libindicator-12.10.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604611474
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1604611474
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libindicator
cp %{_builddir}/libindicator-12.10.1/COPYING %{buildroot}/usr/share/package-licenses/libindicator/8624bcdae55baeef00cd11d5dfcfa60f68710a02
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/libindicator/80indicator-debugging

%files dev
%defattr(-,root,root,-)
/usr/include/libindicator3-0.4/libindicator/indicator-desktop-shortcuts.h
/usr/include/libindicator3-0.4/libindicator/indicator-image-helper.h
/usr/include/libindicator3-0.4/libindicator/indicator-object.h
/usr/include/libindicator3-0.4/libindicator/indicator-service-manager.h
/usr/include/libindicator3-0.4/libindicator/indicator-service.h
/usr/include/libindicator3-0.4/libindicator/indicator.h
/usr/lib64/libdummy-indicator-blank.so
/usr/lib64/libdummy-indicator-entry-func.so
/usr/lib64/libdummy-indicator-null.so
/usr/lib64/libdummy-indicator-signaler.so
/usr/lib64/libdummy-indicator-simple.so
/usr/lib64/libdummy-indicator-visible.so
/usr/lib64/libindicator3.so
/usr/lib64/pkgconfig/indicator3-0.4.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libindicator3.so.7
/usr/lib64/libindicator3.so.7.0.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/indicator-loader3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libindicator/8624bcdae55baeef00cd11d5dfcfa60f68710a02
